services:
  swagger-ui:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./docs/openapi.yaml:/openapi/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miro_clone_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d miro_clone_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: miro_clone_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GO_ENV: development

volumes:
  postgres-data:
  redis-data:
