FROM golang:1.24-alpine AS builder

WORKDIR /build
RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /app/main ./cmd/api

# ---------------------

FROM gcr.io/distroless/static-debian11:nonroot

USER nonroot:nonroot
ENV TZ=Asia/Tokyo

COPY --from=builder --chown=nonroot:nonroot /app/main /app/main

EXPOSE 8000

ENTRYPOINT ["/app/main"]
